version: "2"

services:
  oauth2-server:
    container_name: "oauth2-server"
    image: https://github.com/antoniogamiz/oauth2-server.git
    environment:
      - SERVER_PORT=5000
    volumes:
      - .:/usr/src
    ports:
      - 5000:5000
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null # --quiet
