version: "2"

services:
  oauth2-server:
    container_name: "oauth2"
    image: antoniogamiz/oauth2-server
    command: nodemon --watch src index.js
    env_file:
      - .env
    volumes:
      - .:/usr/src
    ports:
      - 3001:3001
    links:
      - mongodb
    depends_on:
      - mongodb
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    env_file:
      - .env
    volumes:
      - ~/data/db:/data/db
      - ./src/database/mongod.conf:/etc/mongod.conf
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null --config /etc/mongod.conf
